### PR TITLE
Home page

### PR DESCRIPTION
**Pull request by WCanirinka**
I would like my code to be reviewed. Thanks

### CODE REVIEW

**Comment by Anna-Myzukina** [comment]
#### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
### Hi!

### Congratulations you have done a good job in this project 
image

#### Just few changes :

#### Page structure

##### Navigation bar
* [x] It contains Newsweek logo.
* [x] It contains current date.
* [x] It contains Sign in link.
* [x] It contains Subscribe link.
* [x] It contains main navigation links.
* [x] **It changes with RWD breakpoints.**


##### Footer

* [x] It contains Newsweek logo.
* [x] It contains social media icons.
* [x] It contains main navigation links.

*** here should be links ***


*** you can see in original it`s links ***


### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding 😄*

**Comment by WCanirinka** [comment]
Thank you for the review. Kindly review again my code after the changes

**Comment by shshamim63** [comment]
## Status :arrow_right: Approved :arrow_left: 
___
Hi @WCanirinka  :wave: ,
Great job :clap: . Well all the part that are needed to declare this project as done is in here. Nice work :ok_hand: .
___
### [Optional Changes]
On the small device view the the original webpage does not contain singin and subscribe on navbar. But i can see on your one. I believe you can easily fix this issue.
allow1
___
#### This :+1: is from me , you can merge it and don't forget to fill the project completion form.
___
## :clubs: Happy Coding :clubs: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawat-hossain-7750b0127/)| [Slack](Shakhawat Hossain)

**Pull request merged**
